### ISSUE TITLE
ngDevMode problem with Angular 19.2

### ISSUE THREAD

**Issue by GitHubish** [ngneat/helipopper#178]
When I had to upgrade my version of Angular to version 19.2, when I build my project, I get an error telling me that “‘ngDevMode’ was also declared here.”. I have Helipoper version 10.2.0-alpha.2. Do you also have this problem? Thanks

![Image](https://github.com/user-attachments/assets/b51497de-68d9-4727-bce8-27a06d368998)

**Comment by osahner** [comment]
This bug happens even when with the newly released v10.2.0!

**Comment by NetanelBasal** [comment]
We've upgraded to v10.2.0 and we don't have this issue 🤔

**Comment by osahner** [comment]
I try to verify asap

**Comment by KeithGillette** [comment]
We get the same error when updating from 9.2.1 to 10.2.1:
```
Error: node_modules/@ngneat/helipopper/config/tippy.types.d.ts:35:11 - error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

35     const ngDevMode: boolean;
             ~~~~~~~~~

  node_modules/@angular/core/event_dispatcher.d-K56StcHr.d.ts:22:11
    22     const ngDevMode: null | NgDevModePerfCounters;
                 ~~~~~~~~~
    'ngDevMode' was also declared here.
``` 
I'm sure we can mask it with `"skipLibCheck": true in `tsconfig.json`, but it seems to me that this bug report should reopen and the package typing errors corrected.
